/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.so.agi;

import org.jooq.DSLContext;
import org.jooq.Parser;
import org.jooq.Query;
import org.jooq.conf.ParamType;
import org.jooq.conf.Settings;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultConfiguration;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        
        
        
        
        
        DSLContext ctx = DSL.using(
                new DefaultConfiguration().set(
                    new Settings().withParamType(ParamType.FORCE_INDEXED)));

        Parser parser = ctx.parser();
        Query query = parser.parseQuery(
            "select * "
          + "from tableName as t1 "
          + "inner join tableName2 as t2 "
          + "on t1.tableColumnId=t2.tableColumnId "
          + "where t1.tableColumnId=4 and t1.tableColumnName='test'");

        System.out.println(ctx
            .renderContext()
            .paramType(ParamType.FORCE_INDEXED)
            .visit(query)
            .render());

            
        
        
        
        
        
        
        
        
        System.out.println(new App().getGreeting());
    }
}
